SRC = ../srcs/main.cpp
NAME = templates
OBJ_DIR = obj
OBJ = $(patsubst ../srcs/%.cpp, $(OBJ_DIR)/%.o, $(SRC))

all: $(NAME)

$(NAME): $(OBJ)
	c++ -Wall -Wextra -Werror -std=c++98 $(OBJ) -o $(NAME)

$(OBJ_DIR)/%.o: ../srcs/%.cpp | $(OBJ_DIR)
	c++ -Wall -Wextra -Werror -std=c++98 -c $< -o $@

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

clean:
	rm -rf $(OBJ_DIR)

fclean: clean
	rm -rf $(NAME)

re: fclean all

.PHONY: all clean fclean re
